icons:
  #-------------------------------------------------------#
  # ACTIONS                                               #
  #-------------------------------------------------------#

  # Save
  - names:
      - document-save-symbolic
      - document-save
      - filesave
      - gtk-save
      - stock_save
    categories: [actions]
    sizes:
      512: floppy-disk-1.png

  # Save As
  - names:
      - document-save-as-symbolic
      - document-save-as
      - filesaveas
      - gtk-save-as
      - stock_save-as
    categories: [actions]
    sizes:
      512: floppy-disk-with-pen-1.png

  # Cut
  - names:
      - edit-cut
      - edit-cut-symbolic # See: /usr/share/icons/Adwaita/16x16/actions
      - editcut
      - gtk-cut
      - stock_cut
    categories: [actions]
    sizes:
      16: scissors-1.png

  # Copy
  - names:
      - edit-copy
      - edit-copy-symbolic # See: /usr/share/icons/Adwaita/16x16/actions
      - editcopy
      - gtk-copy
      - stock_copy
    categories: [actions]
    sizes:
      16: two-documents-2.png
      512: two-documents-1.png
  
  # Paste
  - names:
      - edit-paste
      - edit-paste-symbolic
      - editpaste
      - gtk-paste
      - stock_paste
    categories: [actions]
    sizes:
      16: clipboard-with-document-1.png
  
  # Delete
  - names:
      - edit-delete
      - edit-delete-symbolic
      - editdelete
      - gtk-delete
      - stock_delete
    categories: [actions]
    sizes:
      16: x-in-red-square-1.png
  
  # Print
  - names:
      - document-print
      - document-print-symbolic # See: /usr/share/icons/Adwaita/16x16/actions
      - fileprint
      - gtk-print
      - stock_print
    categories: [actions]
    sizes:
      16: printer-1.png

  #-------------------------------------------------------#
  # APPLICATIONS                                          #
  #-------------------------------------------------------#

  # TextEdit
  - names:
      - accessories-text-editor
    categories: [apps]
    sizes:
      512: textedit-1.png
  
  # System Preferences, System Settings
  - names:
      - configuration_section
      - control-center2
      - dconf-editor
      - drakconf
      - gconf-editor
      - gconfeditor
      - gkdebconf-icon
      - gkdebconf
      - gnome-desktop-config
      - gnome-settings
      - gtk-preferences
      - org.xfce.settings.manager
      - paprefs
      - preferences-desktop
      - preferences-desktop-personal
      - redhat-preferences
      - redhat-server_settings
      - redhat-tools
      - startupmanager
      - xfce4-mcs-manager
      - xfce4-settings
    categories: [apps, categories]
    sizes:
      512: osx-system-preferences-1.png

  # LibreOffice Writer, Microsoft Word, Word:Mac
  - names:
      - libreoffice-writer
    categories: [apps]
    sizes:
      512: wordmac-1.png
  
  # Chromium, Google Chrome
  - names:
      - chromium
    categories: [apps]
    sizes:
      512: googlechrome-1.png
  
  # Desktop
  - names:
      - cs-desktop
      - desktop
      - gnome-ccdesktop
      - gnome-desktop-config
      - gnome-fs-desktop
      - org.xfce.panel.showdesktop
      - org.xfce.xfdesktop
      - other-desktop
      - user-desktop
      - user-desktop-symbolic
    categories: [apps, places]
    sizes:
      16: osx-place-desktop-2-16x16.png
      48: osx-place-desktop.png
      512: desktop-3.png

  # Effects
  - names:
      - cs-desktop-effects
    categories: [apps, categories]
    sizes:
      48: magicians-hat-1.png

  # Rhythmbox, iTunes
  - names:
      - org.gnome.Rhythmbox
    categories: [apps]
    sizes:
      512: itunes-1.png
  
  # System File Manager, Nemo, Finder
  - names:
      - system-file-manager
    categories: [apps]
    sizes:
      512: osx-finder-2.png

  # App Store, Software Center, Software Manager
  - names:
      - mintinstall
      - softwarecenter
      - softwarecenter-ubuntu
      - softwarecenter-debian
    categories: [apps]
    sizes:
      512: osx-app-store-1.png

  # Firefox
  - names:
      - firefox
      - firefox3
      - firefox-3.0
      - firefox-3.5
      - firefox-4.0
      - firefox-aurora
      - firefox-default
      - firefox-developer-icon
      - firefox-esr
      - firefox-gtk3
      - firefox-icon
      - firefox-nightly
      - firefox-nightly-icon
      - firefox-original
      - firefox-trunk
      - mozilla-firefox
    categories: [apps]
    sizes:
      512: mozilla-firefox-1.png

  #-------------------------------------------------------#
  # PLACES                                                #
  #-------------------------------------------------------#

  # Generic Folder, Directory
  - names:
      - folder
      - folder-drag-accept
      - gnome-folder
      - gnome-fs-directory
      - gnome-fs-directory-accept
      - gtk-directory
      - inode-directory
      - nemo
      - org.xfce.panel.directorymenu
      - stock_folder
    categories: [places]
    sizes:
      16: osx-folder-2-16x16.png
      32: osx-folder-2-32x32.png
      512: osx-folder-1.png

  # Applications Folder, Apps Folder
  - names:
      - application-default-icon
    categories: [places, apps]
    sizes:
      16: osx-place-applications-1-16x16.png
      512: osx-place-applications-1-512x512.png

  # Downloads Folder
  - names:
      - folder-download
      - folder_download
      - folder-downloads
      - folder-downloads-symbolic
    categories: [places]
    sizes:
      16: osx-place-downloads-2-16x16.png
      32: osx-place-downloads-2-32x32.png
      512: osx-folder-downloads-1.png

  # Documents Folder
  - names:
      - folder-documents
      - folders-documents
      - folders-documents-symbolic
    categories: [places]
    sizes:
      16: osx-place-documents-1-16x16.png
      32: osx-place-documents-1-32x32.png
      512: osx-folder-documents-1.png

  # Music Folder
  - names:
      - folder-music
      - folders-music
      - folder-music-symbolic
    categories: [places]
    sizes:
      16: osx-place-music-2-16x16.png
      32: osx-place-music-2-32x32.png
      512: osx-folder-music-1.png

  # Pictures Folder
  - names:
      - folder-pictures
      - folder_pictures
      - folder-pictures-symbolic
    categories: [places]
    sizes:
      16: osx-place-pictures-1-16x16.png
      32: osx-place-pictures-1-32x32.png
      512: osx-folder-pictures-1.png

  # Public Folder, Shared Folder
  - names:
      - folder-publicshare
      - folder-publicshare-symbolic
      - folders-publicshare
    categories: [places]
    sizes:
      16: osx-place-public-1-16x16.png
      32: osx-place-public-1-32x32.png
      512: osx-folder-public-1.png

  # Videos Folder, Movies Folder
  - names:
      - folder-video
      - folder-video-alt
      - folder-videos
      - folder-videos-symbolic
    categories: [places]
    sizes:
      16: osx-place-movies-1-16x16.png
      32: osx-place-movies-1-32x32.png
      512: osx-folder-movies-1.png

  # Home
  - names:
      - folder_home
      - folder-home
      - gnome-fs-home
      - gnome-home
      - user-home
    categories: [places]
    sizes:
      16: osx-home-2-16x16.png
      32: osx-home-2-32x32.png
      512: osx-home-1.png

  # Trash
  - names:
      - edittrash
      - gnome-dev-trash-empty
      - gnome-fs-trash-empty
      - gnome-fs-trash-empty-accept
      - gnome-stock-trash
      - trashcan_empty
      - user-trash
      - xfce-trash_empty
    categories: [places]
    sizes:
      16: osx-trash-empty-2-16x16.png
      512: osx-trash-empty-2.png

  # Full Trash
  - names:
      - gnome-dev-trash-full
      - gnome-fs-trash-full
      - gnome-stock-trash-full
      - stock_trash_full
      - trashcan_full
      - user-trash-full
      - xfce-trash_full
    categories: [places]
    sizes:
      16: osx-trash-full-2-16x16.png
      512: osx-trash-full-2.png
